"""3  migration

Revision ID: 0a8f2ec211c2
Revises: 9c8ae41c92d7
Create Date: 2023-07-24 21:12:42.811009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8f2ec211c2'
down_revision = '9c8ae41c92d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
