"""5  migration

Revision ID: 71b68fd961db
Revises: dfdb628edb57
Create Date: 2023-07-24 22:14:39.628916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b68fd961db'
down_revision = 'dfdb628edb57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
