"""first migration

Revision ID: c2f1c7cde913
Revises: 
Create Date: 2023-07-24 17:20:41.742080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f1c7cde913'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_menu_submenu_id', table_name='menu')
    op.drop_table('menu')
    op.drop_index('ix_submenu_dish_id', table_name='submenu')
    op.drop_index('ix_submenu_name', table_name='submenu')
    op.drop_table('submenu')
    op.drop_index('ix_dishes_name', table_name='dishes')
    op.drop_index('ix_dishes_price', table_name='dishes')
    op.drop_table('dishes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('dishes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dishes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_dishes_price', 'dishes', ['price'], unique=False)
    op.create_index('ix_dishes_name', 'dishes', ['name'], unique=False)
    op.create_table('submenu',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('submenu_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dish_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name='submenu_dish_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='submenu_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_submenu_name', 'submenu', ['name'], unique=False)
    op.create_index('ix_submenu_dish_id', 'submenu', ['dish_id'], unique=False)
    op.create_table('menu',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submenu_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['submenu_id'], ['submenu.id'], name='menu_submenu_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='menu_pkey')
    )
    op.create_index('ix_menu_submenu_id', 'menu', ['submenu_id'], unique=False)
    # ### end Alembic commands ###
