"""3  migration

Revision ID: dfdb628edb57
Revises: 0a8f2ec211c2
Create Date: 2023-07-24 21:26:24.134989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdb628edb57'
down_revision = '0a8f2ec211c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
